### ISSUE TITLE
Improve Development testing Backend

### ISSUE THREAD

**Issue by DellanX** [dipscope/JsonApiEntityProvider.TS#14]
**Is your feature request related to a problem? Please describe.**

In PR #13  we have the issue that querying included objects on toMany relationship requests throws an error due to the SQL server being unable to handle the APPLY operation.

I'd like to discuss a few ideas on upgrading the development environment to be able to run these commands.

**Describe the solution you'd like**

A server capable of running the unit tests.

**Describe alternatives you've considered**

I am considering a few ideas:
1. Looking into the JsonAPI .NET package to see if it can be reconfigured to be able to process these commands without the APPLY operation.
2. Upgrading the development environment's SQL server
3. Upgrading both, by creating a docker image capable of running a MySQL server with the JsonAPI .NET backend
(This one is probably the easiest one for me to implement)

**Additional context**

I am mostly looking for what your preference is before I implement something.
Or, if you're fine with it, I could always add the option for a docker container as a secondary dev environment setup.

**Comment by dpimonov** [comment]
Hi @DellanX, thanks for another interesting proposal. Meantime I've checked already if APPLY command can be supported - answer is no. I am fine on switching to the docker images completely with MySQL provider. 

VS supports container environment using docker-compose. So we can have docker-compose file with 2 containers - one with MySQL and one with .NET application. By clicking the run button - it should start everything the same way as with SQLite. So for me there is not so much difference. You can make a PR. 

Do you already know how to do it in VS? It is one click action and it will create everything including Dockerfile, docker-compose project, start actions and etc. You have to only include mysql image and open proper ports.

**Comment by dpimonov** [comment]
I've replaced everything with docker environment and tested. Works well, all tests pass. If it also works for you - we can close an issue.
