### ISSUE TITLE
Cookies don't send on cross-origin?

### ISSUE THREAD

**Issue by DellanX** [dipscope/JsonApiEntityProvider.TS#17]
**Describe the bug**

I began to deploy my app! Unfortunately, I found another bug in my code during the process.
For some reason or another, my cookies aren't sending in JsonApiEntityProvider requests. They do for the axios requests, and I can see my cookies in the application inspector. I think this has to do with the `credentials` setting on the fetch API called in this library. 

**To Reproduce**

Difficult, as it should be seen in the backend testing already...
My use case, all that changed was that my app went from localhost to localhost:3000. Server stayed the same, localhost:80

**Expected behavior**

I'd expected my app to send the cookies with the request, similar to the axios library.

**Desktop (please complete the following information):**

 - OS: Windows 11 64 bit with WSL2
 - Browser: edge
 - Version: unknown

**Additional context**

At first, I thought CORS, but my dev server has CORS setup to allow http://localhost:3000
I wonder if it is because `credentials` is set to `same-origin`. I am terrible at cookies, but from what I interpreted from a few searches is that this would need to be `include` for my use case. Maybe this could be exposed as a setting, defaulting to `same-origin`?

Also, I don't remember (but hope to look at it soon), but I wonder if the backend is on a different port, but the local testing is without a port (port 80)? Still don't understand how this isn't occurring on the test suite.

Another thing that may be feature worthy, and could resolve this, is documenting how to create a custom connection class. Say I wanted to tie in Axios, or customize my connection configuration? (But that could be another ticket)

**Comment by DellanX** [comment]
I just realized; testing doesn't use cookies... That's why it didn't appear before...

I'll see if I can sideload this project into mine, and see if changing that `credentials` setting fixes the issue.
It does look like Connection is tied to Adapter, and that Adapter is configurable. Maybe the next course of action is that I create my own connection class, and instantiate the adapter within the JsonApiEntityProvider config.

**Comment by dpimonov** [comment]
Hi [DellanX](https://github.com/DellanX), are there any bugs with interceptor so the seperate option is required? Interceptors are designed to change all possible request and response properties. Options you see in the connection are default. One can set custom interceptors during configuration.

```typescript
new JsonApiEntityProvider({
    baseUrl: 'http://localhost:20001',
    jsonApiRequestInterceptor: (request: Request) => new Request(request, { credentials: 'include' })
})
```

About `Axios` - it does not make too much sense to allow connection extension as `fetch API` became a standard when `Node.js` team included it into a core. There are no more difference between frontend requests and backend one. Cross fetch dependency from this library also will be removed on the next major version change.

**Comment by DellanX** [comment]
Oooo, that might work! (I didn't think to recreate the request, and knew that credentials were a readonly variable). I am running into some strange issues, which leads me to think that the properties aren't getting mapped to the new request:
<img width="345" alt="image" src="https://github.com/dipscope/JsonApiEntityProvider.TS/assets/31318348/a1fe1529-fb83-4886-b366-c29307ebf532">
(Should be localhost/users/:id)

I will try for it, worst case, I manually repopulate everything. Luckily the headers and cookies are populated 😀

I will agree that axios itself doesn't make sense to implement at this point. But some projects that use SSR/G may want to be able to inject a custom method to execute the query. (e.g. NUXT has the useFetch composable).

I'm not working on such a project, so, I am definitely not going to push for such a feature. I think the solution you posted will work just fine for my needs.

**Comment by DellanX** [comment]
Disregard, forgot to import Request from 'cross-fetch'
Works like a breeze now. Will cancel my PR!

(Which... I just realized has my name on it because I forgot to configure my username for github...)
