### ISSUE TITLE
Single relationship removal by URL param instead of array body with one entry

### ISSUE THREAD

**Issue by HassanAzzam** [dipscope/JsonApiEntityProvider.TS#30]
My JSON:API server performs single relationship removal by sending a DELETE request with path params and without body, for ex: DELETE `main/2/related/3`.
However, the library in the same case is sending a DELETE request to `main/2/related` with a request body of:
```json
{
    "data": [
        {
            "type": "related",
            "id": "3"
        }
    ]
}
```
although, it's a single entry removal. I know it's convenient for bulk removal but can we change the behavior in the single removal scenario?

**Comment by dpimonov** [comment]
Hi [HassanAzzam](https://github.com/HassanAzzam), I understand your issue but this behaviour will not be changed as we follow [JSON api spec](https://jsonapi.org/format/#crud-updating-relationships) which says:

```
For all request types, the body MUST contain a data member whose value is an empty array or an array of resource identifier objects.
```

We support both scenarios as it is written. 

To remove a `to-one` relationship you have to do the following:

```
const userSet = entityStore.userSet;
const userCompanyRelationship = jsonApiEntityProvider.createJsonApiToOneRelationship(userSet, user, u => u.company);
await userCompany.remove();
```

This will send a PATCH request to remove a relationship. 

In case of `to-many` relationship the method call is kinda similar:

```
const userSet = entityStore.userSet;
const userCompanyRelationship = jsonApiEntityProvider.createJsonApiToManyRelationship(userSet, user, u => u.companies);
await userCompanyRelationship.remove(company);
```

This will send a DELETE request to remove a single relationship as written in the spec. 

You have to find a better server implementation if your current one does not support what a spec says.
