### ISSUE TITLE
How to access error responses?

### ISSUE THREAD

**Issue by judgeaxl** [dipscope/JsonApiEntityProvider.TS#6]
If something goes wrong, JSON:API servers are supposed to return an errors object which can be used to figure out what's wrong, but there doesn't seem to be any way to access this object if a request fails. At best the status and original href is returned.

Since the provider is an implementation detail under EntityStore, perhaps using an interceptor, or listener at the provider level is easier than trying to conform all providers to return errors via a generic interface.

**Comment by dpimonov** [comment]
Can you please describe your use case in more details?

As for now - there are certain error object instances returned depending from error status code. For the most cases this is enough to check if entity was not found and etc. But I am sure you have already noticed them.

![image](https://user-images.githubusercontent.com/15626139/228328183-326093e4-fef0-40a2-94f0-b3a306d33b5a.png)

Basically the errors property which is ruturned from a server is described within types, so we can find a way to use it together with error instances if really required. About generic interface - there are ideas for the future where it will be used on EntityStore level. But this is not related to current issue. 

P.S. I've finished recently a fluent api for TypeManager to describe types without decorators. With it I also considered some of your notes about direct serialization and etc. I plan to switch to EntityStore and will consider your request for missed `find` method when including entities with the next update. Thanks for your feedback and suggestions!

**Comment by judgeaxl** [comment]
First thing that comes to mind is if I violate some constraint when adding or editing an item. The server should give back a reference to the relevant property, like this:

```json
{
  "errors": [
    {
      "source": {
        "pointer": "/data/attributes/name"
      },
      "title": "Xxx must be unique",
      "detail": "The name property must be unique"
    }
  ]
}
```

With JSON:API being more of a hypermedia API than just a REST JSON format, clients are supposed to be able to introspect and act on responses from the server without resorting to a debugger. In the case above it would make sense to show which property is in conflict in the user input form. It would not be feasible to verify what property it is client side, as the set of data might be large and we're only fetching a few pages.

**Comment by dpimonov** [comment]
Usually there is an async check for name uniquness for better user experience. But anyway - providing other specific error makes sense. I am going to think how to combine it with entity store as it operates with entity properties rather then with raw responses.

**Comment by judgeaxl** [comment]
In the meantime, adding a hook for inspecting or logging error responses would be great. I don't really need access to them in the EntityStore API, as I'm trying to capture and debug programmer errors, not necessarily user input errors.

**Comment by dpimonov** [comment]
As a tmp solution we can add error objects returned from api directly to base JsonApiError class so you can access them by catching any exception which is currently thrown by plugin. Will it work for you?

**Comment by judgeaxl** [comment]
Yes, I think that would be very helpful for debugging during development since the JSON:API server does not log posted payloads, for privacy reasons, and there's no other way to easily inspect the traffic from the client side.

I suppose I could override the JsonApiConnection class too, but there's no useful hook so I may end up having to rewrite a lot of it.

Perhaps one could add something like a JsonApiResponseInterceptor, to be run after the response comes back, if configured, allowing deeper inspection or processing. However, putting the error object in the exception will definitely work.

**Comment by dpimonov** [comment]
I have published a beta version with JsonApiResponseInterceptor (i liked an idea - thanks) and document object in exceptions. 

It also includes all latest changes for TypeManager and EntityStore. There are many performance improvements + include support for find command + fluent api for entity configurations + module support on builds. 

I didn't want to include only this change because others were finished. So far all my tests passed so you can try update to the latest major beta version and see if it will work for you. Most of the breaking changes in core packages covers metadata api and in theory should not touch parts which most of the people are using. 

So give it a try and maybe we can close several open issues. If everything works well - I am going to publish all major versions for all projects at the same time.

**Comment by judgeaxl** [comment]
Much appreciated, I will be able to try this out tomorrow

**Comment by judgeaxl** [comment]
I can confirm it works in my setup. I can add this handler to get any errors logged which is all I need for now:

```
          jsonApiResponseInterceptor: (response: Response): Response => {
            if (response.status >= 400 && response.status < 600) {
              response.json().then((json) => {
                logger.error(`${response.status}: ${response.url} - ${JSON.stringify(json)}`)
              })
            }
            return response
          },
```

**Comment by dpimonov** [comment]
Thanks! Glad to hear that! I will write here after updating package versions. Most probably on the weekend.

**Comment by dpimonov** [comment]
Improvement is added in v2.0.0.
